
version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/deployment/

hooks:
  BeforeInstall:
    - location: stop_nginx.sh
    - location: install.sh
  ApplicationStart:
    - location: start_nginx.sh 
