version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html
hooks:
  ApplicationStop:
    - location: deregister_from_elb.sh
    - location: stop_nginx.sh
  files:
  - source: /
    destination: /var/www/html
  install:
    - cd /var/www/html
    - sudo npm install
    - sudo npm start
  ApplicationStart:
    - location: start_nginx.sh
